-- VHDL Entity operative_part_lib.Decoder_counter.interface
--
-- Created:
--          by - e229154f.UNKNOWN (923-P-209517)
--          at - 13:47:46 17/10/2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY Decoder_counter IS
   PORT( 
      DecNbOctet : IN     std_logic;
      NbByteInc  : IN     std_logic;
      din        : OUT    std_logic;
      up_dn      : OUT    std_logic
   );

-- Declarations

END Decoder_counter ;

--
-- VHDL Architecture operative_part_lib.Decoder_counter.tbl
--
-- Created:
--          by - e229154f.UNKNOWN (923-P-209517)
--          at - 13:47:46 17/10/2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
ARCHITECTURE tbl OF Decoder_counter IS
   
      -- Architecture declarations
    

BEGIN

   -----------------------------------------------------------------
   truth_process_proc: PROCESS(DecNbOctet, NbByteInc)
   -----------------------------------------------------------------
   BEGIN
      -- Block 1
      IF (DecNbOctet = '0') AND (NbByteInc = '0') THEN
         din <= '0';
         up_dn <= '1';
      ELSIF (DecNbOctet = '0') AND (NbByteInc = '1') THEN
         din <= '1';
         up_dn <= '1';
      ELSIF (DecNbOctet = '1') AND (NbByteInc = '0') THEN
         din <= '1';
         up_dn <= '0';
      ELSIF (DecNbOctet = '1') AND (NbByteInc = '1') THEN
         din <= '0';
         up_dn <= '0';
      END IF;

   END PROCESS truth_process_proc;

-- Architecture concurrent statements
 

END tbl;
