-- VHDL Entity operative_part_lib.FIFO.interface
--
-- Created:
--          by - e229154f.UNKNOWN (923-P-209517)
--          at - 13:36:17 17/10/2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY FIFO IS
   PORT( 
      H           : IN     std_logic;
      OctetLu_RD  : IN     std_logic;
      RecByte     : IN     std_logic_vector (7 DOWNTO 0);
      RecByte_RST : IN     std_logic;
      RecByte_WR  : IN     std_logic;
      nCLR        : IN     std_logic;
      OctetLu     : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END FIFO ;

--
-- VHDL Architecture operative_part_lib.FIFO.struct
--
-- Created:
--          by - e229154f.UNKNOWN (923-P-209517)
--          at - 13:13:51 17/10/2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF FIFO IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_0' of 'fifo'
   TYPE mw_U_0sreg IS ARRAY (8 DOWNTO 0) OF std_logic_vector(7 DOWNTO 0);
   SIGNAL mw_U_0addr_cval : INTEGER RANGE 0 TO 8;
   SIGNAL mw_U_0addr_nval : INTEGER RANGE 0 TO 8;
   SIGNAL mw_U_0reg_cval : mw_U_0sreg;
   SIGNAL mw_U_0reg_nval : mw_U_0sreg;


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'fifo'
   OctetLu <= mw_U_0reg_cval(0);
   u_0seq1_proc: PROCESS (H)
   BEGIN
      IF (H'EVENT AND H='1') THEN
         FOR i IN 0 TO 8 LOOP
            mw_U_0reg_cval(i)(7 DOWNTO 0) <= mw_U_0reg_nval(i)(7 DOWNTO 0);
         END LOOP;
      END IF;
   END PROCESS u_0seq1_proc;
   
   u_0seq2_proc: PROCESS (H, dout)
   BEGIN
      IF (dout = '0') THEN
         mw_U_0addr_cval <= 0;
      ELSIF (H'EVENT AND H='1') THEN
         mw_U_0addr_cval <= mw_U_0addr_nval;
      END IF;
   END PROCESS u_0seq2_proc;
   
   u_0combo_proc: PROCESS (dout, OctetLu_RD, RecByte_WR, mw_U_0addr_cval, mw_U_0reg_cval, RecByte)
   VARIABLE temp_rena : std_logic;
   VARIABLE temp_wena : std_logic;
   VARIABLE temp_full : std_logic;
   VARIABLE temp_empty : std_logic;
   BEGIN
      IF (mw_U_0addr_cval = 8) THEN
         temp_full := '1';
         temp_empty := '0';
      ELSIF (mw_U_0addr_cval = 0) THEN
         temp_full := '0';
         temp_empty := '1';
      ELSE
         temp_full := '0';
         temp_empty := '0';
      END IF;
      temp_rena := dout AND OctetLu_RD AND NOT(temp_empty);
      temp_wena := dout AND RecByte_WR AND NOT(temp_full);
   
      IF (temp_wena = '1') THEN
         mw_U_0addr_nval <= mw_U_0addr_cval + 1;
      ELSIF (temp_rena = '1') THEN
         mw_U_0addr_nval <= mw_U_0addr_cval - 1;
      ELSE
         mw_U_0addr_nval <= mw_U_0addr_cval;
      END IF;
   
      IF (temp_wena = '1') THEN
         mw_U_0reg_nval(0)(7 DOWNTO 0) <= mw_U_0reg_cval(0)(7 DOWNTO 0);
         FOR i IN 0 TO 7 LOOP
            IF (mw_U_0addr_cval = i) THEN
               mw_U_0reg_nval(i+1)(7 DOWNTO 0) <= RecByte;
            ELSE
               mw_U_0reg_nval(i+1)(7 DOWNTO 0) <= mw_U_0reg_cval(i+1)(7 DOWNTO 0);
            END IF;
         END LOOP;
      ELSIF (temp_wena = '0') THEN
         IF (temp_rena = '1') THEN
            FOR i IN 0 TO 7 LOOP
               mw_U_0reg_nval(i)(7 DOWNTO 0) <= mw_U_0reg_cval(i+1)(7 DOWNTO 0);
            END LOOP;
            mw_U_0reg_nval(8)(7 DOWNTO 0) <= mw_U_0reg_cval(8)(7 DOWNTO 0);
         ELSIF (temp_rena = '0') THEN
            FOR i IN 0 TO 8 LOOP
               mw_U_0reg_nval(i)(7 DOWNTO 0) <= mw_U_0reg_cval(i)(7 DOWNTO 0);
            END LOOP;
         ELSE
            FOR i IN 0 TO 8 LOOP
               mw_U_0reg_nval(i)(7 DOWNTO 0) <= (OTHERS => 'X');
            END LOOP;
         END IF;
      ELSE
         FOR i IN 0 TO 8 LOOP
            mw_U_0reg_nval(i)(7 DOWNTO 0) <= (OTHERS => 'X');
         END LOOP;
      END IF;
   END PROCESS u_0combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'or'
   dout <= nCLR OR RecByte_RST;

   -- Instance port mappings.

END struct;
