-- VHDL Entity operative_part_lib.Internal_state.interface
--
-- Created:
--          by - e229154f.UNKNOWN (923-P-209517)
--          at - 13:36:30 17/10/2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY Internal_state IS
   PORT( 
      DecNbOctet          : IN     std_logic;
      Error_start         : IN     std_logic;
      Error_stop          : IN     std_logic;
      Error_synchro       : IN     std_logic;
      EtatLu_RST          : IN     std_logic;
      H                   : IN     std_logic;
      MessageReceived_SET : IN     std_logic;
      NbByteInc           : IN     std_logic;
      NbRecByte_RST       : IN     std_logic;
      nCLR                : IN     std_logic;
      EtatLu              : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END Internal_state ;

--
-- VHDL Architecture operative_part_lib.Internal_state.struct
--
-- Created:
--          by - e229154f.UNKNOWN (923-P-209517)
--          at - 14:56:17 17/10/2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY operative_part_lib;

ARCHITECTURE struct OF Internal_state IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL count : std_logic_vector(3 DOWNTO 0);
   SIGNAL din   : std_logic;
   SIGNAL din1  : std_logic;
   SIGNAL din3  : std_logic;
   SIGNAL dout  : std_logic_vector(3 DOWNTO 0);
   SIGNAL q     : std_logic;
   SIGNAL q1    : std_logic;
   SIGNAL r     : std_logic;
   SIGNAL up_dn : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_9' of 'cntr'
   SIGNAL mw_U_9n_cnt : std_logic_vector(3 DOWNTO 0);
   SIGNAL mw_U_9c_cnt : std_logic_vector(3 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_2' of 'rsff'
   SIGNAL mw_U_2reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.12) for instance 'U_4' of 'rsff'
   SIGNAL mw_U_4reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.12) for instance 'U_6' of 'rsff'
   SIGNAL mw_U_6reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.12) for instance 'U_8' of 'rsff'
   SIGNAL mw_U_8reg_cval : std_logic;

   -- Component Declarations
   COMPONENT Decoder_counter
   PORT (
      DecNbOctet : IN     std_logic ;
      NbByteInc  : IN     std_logic ;
      din        : OUT    std_logic ;
      up_dn      : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : Decoder_counter USE ENTITY operative_part_lib.Decoder_counter;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_9' of 'cntr'
   count <= mw_U_9c_cnt;
   u_9clock_proc: PROCESS (H, nCLR)
   BEGIN
      IF (nCLR = '0') THEN
         mw_U_9c_cnt <= "0000";
      ELSIF (H'EVENT AND H='1') THEN
         IF (din = '1') THEN
            mw_U_9c_cnt <= mw_U_9n_cnt;
         END IF;
      END IF;
   END PROCESS u_9clock_proc;
   u_9combo_proc: PROCESS (NbRecByte_RST, dout, up_dn, mw_U_9c_cnt)
   -- up = '1', dn = '0'
   BEGIN
      IF (NbRecByte_RST = '1') THEN
         mw_U_9n_cnt <= dout;
      ELSE
         IF (up_dn = '1') THEN
            IF (mw_U_9c_cnt = "1111") THEN
               mw_U_9n_cnt <= (OTHERS => '0');
            ELSE
               mw_U_9n_cnt <= (unsigned(mw_U_9c_cnt) + '1');
            END IF;
         ELSE
            IF (mw_U_9c_cnt = "0000") THEN
               mw_U_9n_cnt <= "1111";
            ELSE
               mw_U_9n_cnt <= (unsigned(mw_U_9c_cnt) - '1');
            END IF;
         END IF;
      END IF;
   END PROCESS u_9combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_3' of 'constval'
   dout <= "0000";

   -- ModuleWare code(v1.12) for instance 'U_0' of 'merge'
   EtatLu <= count & din3 & q1 & din1 & q;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'or'
   r <= EtatLu_RST OR NbRecByte_RST;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'rsff'
   q <= mw_U_2reg_cval;
   u_2seq_proc: PROCESS (H, nCLR)
   BEGIN
      IF (nCLR = '0') THEN
         mw_U_2reg_cval <= '0';
      ELSIF (H'EVENT AND H='1') THEN
         IF (r = '1') THEN
            mw_U_2reg_cval <= '0';
         ELSIF (Error_start = '1') THEN
            mw_U_2reg_cval <= '1';
         END IF;
      END IF;
   END PROCESS u_2seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'rsff'
   din1 <= mw_U_4reg_cval;
   u_4seq_proc: PROCESS (H, nCLR)
   BEGIN
      IF (nCLR = '0') THEN
         mw_U_4reg_cval <= '0';
      ELSIF (H'EVENT AND H='1') THEN
         IF (r = '1') THEN
            mw_U_4reg_cval <= '0';
         ELSIF (Error_stop = '1') THEN
            mw_U_4reg_cval <= '1';
         END IF;
      END IF;
   END PROCESS u_4seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_6' of 'rsff'
   q1 <= mw_U_6reg_cval;
   u_6seq_proc: PROCESS (H, nCLR)
   BEGIN
      IF (nCLR = '0') THEN
         mw_U_6reg_cval <= '0';
      ELSIF (H'EVENT AND H='1') THEN
         IF (r = '1') THEN
            mw_U_6reg_cval <= '0';
         ELSIF (Error_synchro = '1') THEN
            mw_U_6reg_cval <= '1';
         END IF;
      END IF;
   END PROCESS u_6seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_8' of 'rsff'
   din3 <= mw_U_8reg_cval;
   u_8seq_proc: PROCESS (H, nCLR)
   BEGIN
      IF (nCLR = '0') THEN
         mw_U_8reg_cval <= '0';
      ELSIF (H'EVENT AND H='1') THEN
         IF (r = '1') THEN
            mw_U_8reg_cval <= '0';
         ELSIF (MessageReceived_SET = '1') THEN
            mw_U_8reg_cval <= '1';
         END IF;
      END IF;
   END PROCESS u_8seq_proc;

   -- Instance port mappings.
   U_10 : Decoder_counter
      PORT MAP (
         DecNbOctet => DecNbOctet,
         NbByteInc  => NbByteInc,
         din        => din,
         up_dn      => up_dn
      );

END struct;
