-- VHDL Entity operative_part_lib.lin_receiver.symbol
--
-- Created:
--          by - e229154f.UNKNOWN (923-P-209517)
--          at - 14:53:23 17/10/2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY lin_receiver IS
   PORT( 
      CnD        : IN     std_logic;
      H          : IN     std_logic;
      RnW        : IN     std_logic;
      lin        : IN     std_logic;
      nCLR       : IN     std_logic;
      nCS        : IN     std_logic;
      M_Received : OUT    std_logic;
      D07        : INOUT  std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END lin_receiver ;

--
-- VHDL Architecture operative_part_lib.lin_receiver.struct
--
-- Created:
--          by - e229154f.UNKNOWN (923-P-209517)
--          at - 14:53:23 17/10/2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY operative_part_lib;

ARCHITECTURE struct OF lin_receiver IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL DecNbOctet          : std_logic;
   SIGNAL Error_start         : std_logic;
   SIGNAL Error_stop          : std_logic;
   SIGNAL Error_synchro       : std_logic;
   SIGNAL EtatLu              : std_logic_vector(7 DOWNTO 0);
   SIGNAL EtatLu_RST          : std_logic;
   SIGNAL MessageReceived_SET : std_logic;
   SIGNAL NbByteInc           : std_logic;
   SIGNAL NbRecByte_RST       : std_logic;
   SIGNAL OctetLu             : std_logic_vector(7 DOWNTO 0);
   SIGNAL OctetLu_RD          : std_logic;
   SIGNAL RecByte             : std_logic_vector(7 DOWNTO 0);
   SIGNAL RecByte_RST         : std_logic;
   SIGNAL RecByte_WR          : std_logic;
   SIGNAL SelAdr              : std_logic_vector(7 DOWNTO 0);


   -- Component Declarations
   COMPONENT FIFO
   PORT (
      H           : IN     std_logic ;
      OctetLu_RD  : IN     std_logic ;
      RecByte     : IN     std_logic_vector (7 DOWNTO 0);
      RecByte_RST : IN     std_logic ;
      RecByte_WR  : IN     std_logic ;
      nCLR        : IN     std_logic ;
      OctetLu     : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT InterfaceMicroprocesseur
   PORT (
      CnD        : IN     std_logic ;
      OctetLu    : IN     std_logic_vector (7 DOWNTO 0);
      EtatLu     : IN     std_logic_vector (7 DOWNTO 0);
      H          : IN     std_logic ;
      RnW        : IN     std_logic ;
      nCS        : IN     std_logic ;
      nRST       : IN     std_logic ;
      DecNbOctet : OUT    std_logic ;
      SelAdr     : OUT    std_logic_vector (7 DOWNTO 0);
      M_Received : OUT    std_logic ;
      EtatLu_RST : OUT    std_logic ;
      OctetLu_RD : OUT    std_logic ;
      D07        : INOUT  std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT Internal_state
   PORT (
      DecNbOctet          : IN     std_logic ;
      Error_start         : IN     std_logic ;
      Error_stop          : IN     std_logic ;
      Error_synchro       : IN     std_logic ;
      EtatLu_RST          : IN     std_logic ;
      H                   : IN     std_logic ;
      MessageReceived_SET : IN     std_logic ;
      NbByteInc           : IN     std_logic ;
      NbRecByte_RST       : IN     std_logic ;
      nCLR                : IN     std_logic ;
      EtatLu              : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT lin_processing
   PORT (
      H                   : IN     std_logic ;
      SelAdr              : IN     std_logic_vector (7 DOWNTO 0);
      lin                 : IN     std_logic ;
      nCLR                : IN     std_logic ;
      Error_start         : OUT    std_logic ;
      Error_stop          : OUT    std_logic ;
      Error_synchro       : OUT    std_logic ;
      MessageReceived_SET : OUT    std_logic ;
      NbByteInc           : OUT    std_logic ;
      NbRecByte_RST       : OUT    std_logic ;
      RecByte             : OUT    std_logic_vector (7 DOWNTO 0);
      RecByte_RST         : OUT    std_logic ;
      RecByte_WR          : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : FIFO USE ENTITY operative_part_lib.FIFO;
   FOR ALL : InterfaceMicroprocesseur USE ENTITY operative_part_lib.InterfaceMicroprocesseur;
   FOR ALL : Internal_state USE ENTITY operative_part_lib.Internal_state;
   FOR ALL : lin_processing USE ENTITY operative_part_lib.lin_processing;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   FirstInFO : FIFO
      PORT MAP (
         H           => H,
         OctetLu_RD  => OctetLu_RD,
         RecByte     => RecByte,
         RecByte_RST => RecByte_RST,
         RecByte_WR  => RecByte_WR,
         nCLR        => nCLR,
         OctetLu     => OctetLu
      );
   Interface_micro : InterfaceMicroprocesseur
      PORT MAP (
         CnD        => CnD,
         OctetLu    => OctetLu,
         EtatLu     => EtatLu,
         H          => H,
         RnW        => RnW,
         nCS        => nCS,
         nRST       => nCLR,
         DecNbOctet => DecNbOctet,
         SelAdr     => SelAdr,
         M_Received => M_Received,
         EtatLu_RST => EtatLu_RST,
         OctetLu_RD => OctetLu_RD,
         D07        => D07
      );
   Intern_state : Internal_state
      PORT MAP (
         DecNbOctet          => DecNbOctet,
         Error_start         => Error_start,
         Error_stop          => Error_stop,
         Error_synchro       => Error_synchro,
         EtatLu_RST          => EtatLu_RST,
         H                   => H,
         MessageReceived_SET => MessageReceived_SET,
         NbByteInc           => NbByteInc,
         NbRecByte_RST       => NbRecByte_RST,
         nCLR                => nCLR,
         EtatLu              => EtatLu
      );
   OP_part : lin_processing
      PORT MAP (
         H                   => H,
         SelAdr              => SelAdr,
         lin                 => lin,
         nCLR                => nCLR,
         Error_start         => Error_start,
         Error_stop          => Error_stop,
         Error_synchro       => Error_synchro,
         MessageReceived_SET => MessageReceived_SET,
         NbByteInc           => NbByteInc,
         NbRecByte_RST       => NbRecByte_RST,
         RecByte             => RecByte,
         RecByte_RST         => RecByte_RST,
         RecByte_WR          => RecByte_WR
      );

END struct;
