-- VHDL Entity operative_part_lib.lin_processing.symbol
--
-- Created:
--          by - e229154f.UNKNOWN (923-P-209517)
--          at - 14:20:47 17/10/2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY lin_processing IS
   PORT( 
      H                   : IN     std_logic;
      SelAdr              : IN     std_logic_vector (7 DOWNTO 0);
      lin                 : IN     std_logic;
      nCLR                : IN     std_logic;
      Error_start         : OUT    std_logic;
      Error_stop          : OUT    std_logic;
      Error_synchro       : OUT    std_logic;
      MessageReceived_SET : OUT    std_logic;
      NbByteInc           : OUT    std_logic;
      NbRecByte_RST       : OUT    std_logic;
      RecByte             : OUT    std_logic_vector (7 DOWNTO 0);
      RecByte_RST         : OUT    std_logic;
      RecByte_WR          : OUT    std_logic
   );

-- Declarations

END lin_processing ;

--
-- VHDL Architecture operative_part_lib.lin_processing.struct
--
-- Created:
--          by - e229154f.UNKNOWN (923-P-209517)
--          at - 14:20:47 17/10/2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY operative_part_lib;

ARCHITECTURE struct OF lin_processing IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL DataFieldNb_0      : std_logic;
   SIGNAL DataFieldNb_EN     : std_logic;
   SIGNAL DataFieldNb_LOAD   : std_logic;
   SIGNAL IdentifierField_EN : std_logic;
   SIGNAL LinSynchro         : std_logic;
   SIGNAL NbBit_0            : std_logic;
   SIGNAL NbBit_EN           : std_logic;
   SIGNAL NbBit_LOAD         : std_logic;
   SIGNAL NbBit_SELECT       : std_logic;
   SIGNAL RecByte_EN         : std_logic;
   SIGNAL n_0                : std_logic;
   SIGNAL n_EN               : std_logic;
   SIGNAL n_LOAD             : std_logic;
   SIGNAL n_SELECT           : std_logic;


   -- Component Declarations
   COMPONENT command_unit
   PORT (
      DataFieldNb_0       : IN     std_logic ;
      H                   : IN     std_logic ;
      LinSynchro          : IN     std_logic ;
      NbBit_0             : IN     std_logic ;
      SelAdr              : IN     std_logic_vector (7 DOWNTO 0);
      nCLR                : IN     std_logic ;
      n_0                 : IN     std_logic ;
      DataFieldNb_EN      : OUT    std_logic ;
      DataFieldNb_Load    : OUT    std_logic ;
      Error_start         : OUT    std_logic ;
      Error_stop          : OUT    std_logic ;
      Error_synchro       : OUT    std_logic ;
      IdentifierField_EN  : OUT    std_logic ;
      MessageReceived_SET : OUT    std_logic ;
      NbBit_EN            : OUT    std_logic ;
      NbBit_LOAD          : OUT    std_logic ;
      NbBit_SELECT        : OUT    std_logic ;
      NbByteInc           : OUT    std_logic ;
      NbRecByte_RST       : OUT    std_logic ;
      RecByte_EN          : OUT    std_logic ;
      RecByte_RST         : OUT    std_logic ;
      RecByte_WR          : OUT    std_logic ;
      n_EN                : OUT    std_logic ;
      n_LOAD              : OUT    std_logic ;
      n_SELECT            : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT operative_part
   PORT (
      BitsNb_EN          : IN     std_logic ;
      BitsNb_LOAD        : IN     std_logic ;
      BitsNb_SELECT      : IN     std_logic ;
      DataFieldNb_EN     : IN     std_logic ;
      DataFieldNb_LOAD   : IN     std_logic ;
      H                  : IN     std_logic ;
      IdentifierField_EN : IN     std_logic ;
      RecByte_EN         : IN     std_logic ;
      lin                : IN     std_logic ;
      nCLR               : IN     std_logic ;
      n_EN               : IN     std_logic ;
      n_LOAD             : IN     std_logic ;
      n_SELECT           : IN     std_logic ;
      BitsNb             : OUT    std_logic_vector (3 DOWNTO 0);
      BitsNb_0           : OUT    std_logic ;
      DataFieldNb        : OUT    std_logic_vector (2 DOWNTO 0);
      DataFieldNb_0      : OUT    std_logic ;
      IdentifierField    : OUT    std_logic_vector (5 DOWNTO 0);
      LinSynchro         : OUT    std_logic ;
      RecByte            : OUT    std_logic_vector (7 DOWNTO 0);
      n                  : OUT    std_logic_vector (10 DOWNTO 0);
      n_0                : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : command_unit USE ENTITY operative_part_lib.command_unit;
   FOR ALL : operative_part USE ENTITY operative_part_lib.operative_part;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : command_unit
      PORT MAP (
         DataFieldNb_0       => DataFieldNb_0,
         H                   => H,
         LinSynchro          => LinSynchro,
         NbBit_0             => NbBit_0,
         SelAdr              => SelAdr,
         nCLR                => nCLR,
         n_0                 => n_0,
         DataFieldNb_EN      => DataFieldNb_EN,
         DataFieldNb_Load    => DataFieldNb_LOAD,
         Error_start         => Error_start,
         Error_stop          => Error_stop,
         Error_synchro       => Error_synchro,
         IdentifierField_EN  => IdentifierField_EN,
         MessageReceived_SET => MessageReceived_SET,
         NbBit_EN            => NbBit_EN,
         NbBit_LOAD          => NbBit_LOAD,
         NbBit_SELECT        => NbBit_SELECT,
         NbByteInc           => NbByteInc,
         NbRecByte_RST       => NbRecByte_RST,
         RecByte_EN          => RecByte_EN,
         RecByte_RST         => RecByte_RST,
         RecByte_WR          => RecByte_WR,
         n_EN                => n_EN,
         n_LOAD              => n_LOAD,
         n_SELECT            => n_SELECT
      );
   U_1 : operative_part
      PORT MAP (
         BitsNb_EN          => NbBit_EN,
         BitsNb_LOAD        => NbBit_LOAD,
         BitsNb_SELECT      => NbBit_SELECT,
         DataFieldNb_EN     => DataFieldNb_EN,
         DataFieldNb_LOAD   => DataFieldNb_LOAD,
         H                  => H,
         IdentifierField_EN => IdentifierField_EN,
         RecByte_EN         => RecByte_EN,
         lin                => lin,
         nCLR               => nCLR,
         n_EN               => n_EN,
         n_LOAD             => n_LOAD,
         n_SELECT           => n_SELECT,
         BitsNb             => OPEN,
         BitsNb_0           => NbBit_0,
         DataFieldNb        => OPEN,
         DataFieldNb_0      => DataFieldNb_0,
         IdentifierField    => OPEN,
         LinSynchro         => LinSynchro,
         RecByte            => RecByte,
         n                  => OPEN,
         n_0                => n_0
      );

END struct;
