-- VHDL Entity operative_part_lib.operative_part.symbol
--
-- Created:
--          by - e229154f.UNKNOWN (923-P-209517)
--          at - 16:16:18 02/10/2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY operative_part IS
   PORT( 
      BitsNb_EN          : IN     std_logic;
      BitsNb_LOAD        : IN     std_logic;
      BitsNb_SELECT      : IN     std_logic;
      DataFieldNb_EN     : IN     std_logic;
      DataFieldNb_LOAD   : IN     std_logic;
      H                  : IN     std_logic;
      IdentifierField_EN : IN     std_logic;
      RecByte_EN         : IN     std_logic;
      lin                : IN     std_logic;
      nCLR               : IN     std_logic;
      n_EN               : IN     std_logic;
      n_LOAD             : IN     std_logic;
      n_SELECT           : IN     std_logic;
      BitsNb             : OUT    std_logic_vector (3 DOWNTO 0);
      BitsNb_0           : OUT    std_logic;
      DataFieldNb        : OUT    std_logic_vector (2 DOWNTO 0);
      DataFieldNb_0      : OUT    std_logic;
      IdentifierField    : OUT    std_logic_vector (5 DOWNTO 0);
      LinSynchro         : OUT    std_logic;
      RecByte            : OUT    std_logic_vector (7 DOWNTO 0);
      n                  : OUT    std_logic_vector (10 DOWNTO 0);
      n_0                : OUT    std_logic
   );

-- Declarations

END operative_part ;

--
-- VHDL Architecture operative_part_lib.operative_part.struct
--
-- Created:
--          by - e229154f.UNKNOWN (923-P-209517)
--          at - 16:16:18 02/10/2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY operative_part_lib;

ARCHITECTURE struct OF operative_part IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL DataFieldNb_INIT : std_logic_vector(2 DOWNTO 0);
   SIGNAL Ndiv2            : std_logic_vector(10 DOWNTO 0);
   SIGNAL Nmoins1          : std_logic_vector(10 DOWNTO 0);
   SIGNAL din1             : std_logic_vector(3 DOWNTO 0);
   SIGNAL dout             : std_logic_vector(10 DOWNTO 0);
   SIGNAL dout1            : std_logic;
   SIGNAL dout2            : std_logic_vector(3 DOWNTO 0);
   SIGNAL dout3            : std_logic_vector(3 DOWNTO 0);
   SIGNAL dout4            : std_logic;
   SIGNAL dout5            : std_logic;
   SIGNAL dout6            : std_logic;

   -- Implicit buffer signal declarations
   SIGNAL LinSynchro_internal : std_logic;
   SIGNAL RecByte_internal    : std_logic_vector (7 DOWNTO 0);


   -- ModuleWare signal declarations(v1.12) for instance 'U_0' of 'adff'
   SIGNAL mw_U_0reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.12) for instance 'U_1' of 'cntr'
   SIGNAL mw_U_1n_cnt : std_logic_vector(10 DOWNTO 0);
   SIGNAL mw_U_1c_cnt : std_logic_vector(10 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_2' of 'cntr'
   SIGNAL mw_U_2n_cnt : std_logic_vector(2 DOWNTO 0);
   SIGNAL mw_U_2c_cnt : std_logic_vector(2 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_3' of 'cntr'
   SIGNAL mw_U_3n_cnt : std_logic_vector(3 DOWNTO 0);
   SIGNAL mw_U_3c_cnt : std_logic_vector(3 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_14' of 'dff'
   SIGNAL mw_U_14reg_cval : std_logic_vector(5 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_4' of 'shiftsp'
   SIGNAL mw_U_4reg_cval : std_logic_vector(7 DOWNTO 0);
   SIGNAL mw_U_4reg_nval : std_logic_vector(7 DOWNTO 0);

   -- Component Declarations
   COMPONENT Decoder
   PORT (
      RecByte          : IN     std_logic_vector (5 DOWNTO 4);
      DataFieldNb_INIT : OUT    std_logic_vector (2 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : Decoder USE ENTITY operative_part_lib.Decoder;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'adff'
   LinSynchro_internal <= mw_U_0reg_cval;
   u_0seq_proc: PROCESS (H, nCLR)
   BEGIN
      IF (nCLR = '0') THEN
         mw_U_0reg_cval <= '1';
      ELSIF (H'EVENT AND H='1') THEN
         mw_U_0reg_cval <= lin;
      END IF;
   END PROCESS u_0seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'cntr'
   n <= mw_U_1c_cnt;
   u_1clock_proc: PROCESS (H, nCLR)
   BEGIN
      IF (nCLR = '0') THEN
         mw_U_1c_cnt <= "00000000000";
      ELSIF (H'EVENT AND H='1') THEN
         IF (n_EN = '1') THEN
            mw_U_1c_cnt <= mw_U_1n_cnt;
         END IF;
      END IF;
   END PROCESS u_1clock_proc;
   u_1combo_proc: PROCESS (n_LOAD, dout, dout1, mw_U_1c_cnt)
   -- up = '1', dn = '0'
   BEGIN
      IF (n_LOAD = '1') THEN
         mw_U_1n_cnt <= dout;
      ELSE
         IF (dout1 = '1') THEN
            IF (mw_U_1c_cnt = "11111111111") THEN
               mw_U_1n_cnt <= (OTHERS => '0');
            ELSE
               mw_U_1n_cnt <= (unsigned(mw_U_1c_cnt) + '1');
            END IF;
         ELSE
            IF (mw_U_1c_cnt = "00000000000") THEN
               mw_U_1n_cnt <= "11111111111";
            ELSE
               mw_U_1n_cnt <= (unsigned(mw_U_1c_cnt) - '1');
            END IF;
         END IF;
      END IF;
   END PROCESS u_1combo_proc;
   u_1max_drive_proc: PROCESS (mw_U_1c_cnt, dout1)
   BEGIN
      n_0 <= '0';
      IF (dout1 = '1') THEN
         IF (mw_U_1c_cnt = "11111111111") THEN
            n_0 <= '1';
         END IF;
      ELSE
         IF (mw_U_1c_cnt = "00000000000") THEN
            n_0 <= '1';
         END IF;
      END IF;
   END PROCESS u_1max_drive_proc;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'cntr'
   DataFieldNb <= mw_U_2c_cnt;
   u_2clock_proc: PROCESS (H, nCLR)
   BEGIN
      IF (nCLR = '0') THEN
         mw_U_2c_cnt <= "000";
      ELSIF (H'EVENT AND H='1') THEN
         IF (DataFieldNb_EN = '1') THEN
            mw_U_2c_cnt <= mw_U_2n_cnt;
         END IF;
      END IF;
   END PROCESS u_2clock_proc;
   u_2combo_proc: PROCESS (DataFieldNb_LOAD, DataFieldNb_INIT, dout5, mw_U_2c_cnt)
   -- up = '1', dn = '0'
   BEGIN
      IF (DataFieldNb_LOAD = '1') THEN
         mw_U_2n_cnt <= DataFieldNb_INIT;
      ELSE
         IF (dout5 = '1') THEN
            IF (mw_U_2c_cnt = "111") THEN
               mw_U_2n_cnt <= (OTHERS => '0');
            ELSE
               mw_U_2n_cnt <= (unsigned(mw_U_2c_cnt) + '1');
            END IF;
         ELSE
            IF (mw_U_2c_cnt = "000") THEN
               mw_U_2n_cnt <= "111";
            ELSE
               mw_U_2n_cnt <= (unsigned(mw_U_2c_cnt) - '1');
            END IF;
         END IF;
      END IF;
   END PROCESS u_2combo_proc;
   u_2max_drive_proc: PROCESS (mw_U_2c_cnt, dout5)
   BEGIN
      DataFieldNb_0 <= '0';
      IF (dout5 = '1') THEN
         IF (mw_U_2c_cnt = "111") THEN
            DataFieldNb_0 <= '1';
         END IF;
      ELSE
         IF (mw_U_2c_cnt = "000") THEN
            DataFieldNb_0 <= '1';
         END IF;
      END IF;
   END PROCESS u_2max_drive_proc;

   -- ModuleWare code(v1.12) for instance 'U_3' of 'cntr'
   BitsNb <= mw_U_3c_cnt;
   u_3clock_proc: PROCESS (H, nCLR)
   BEGIN
      IF (nCLR = '0') THEN
         mw_U_3c_cnt <= "0000";
      ELSIF (H'EVENT AND H='1') THEN
         IF (BitsNb_EN = '1') THEN
            mw_U_3c_cnt <= mw_U_3n_cnt;
         END IF;
      END IF;
   END PROCESS u_3clock_proc;
   u_3combo_proc: PROCESS (BitsNb_LOAD, dout3, dout4, mw_U_3c_cnt)
   -- up = '1', dn = '0'
   BEGIN
      IF (BitsNb_LOAD = '1') THEN
         mw_U_3n_cnt <= dout3;
      ELSE
         IF (dout4 = '1') THEN
            IF (mw_U_3c_cnt = "1111") THEN
               mw_U_3n_cnt <= (OTHERS => '0');
            ELSE
               mw_U_3n_cnt <= (unsigned(mw_U_3c_cnt) + '1');
            END IF;
         ELSE
            IF (mw_U_3c_cnt = "0000") THEN
               mw_U_3n_cnt <= "1111";
            ELSE
               mw_U_3n_cnt <= (unsigned(mw_U_3c_cnt) - '1');
            END IF;
         END IF;
      END IF;
   END PROCESS u_3combo_proc;
   u_3max_drive_proc: PROCESS (mw_U_3c_cnt, dout4)
   BEGIN
      BitsNb_0 <= '0';
      IF (dout4 = '1') THEN
         IF (mw_U_3c_cnt = "1111") THEN
            BitsNb_0 <= '1';
         END IF;
      ELSE
         IF (mw_U_3c_cnt = "0000") THEN
            BitsNb_0 <= '1';
         END IF;
      END IF;
   END PROCESS u_3max_drive_proc;

   -- ModuleWare code(v1.12) for instance 'U_8' of 'constval'
   dout1 <= '0';

   -- ModuleWare code(v1.12) for instance 'U_9' of 'constval'
   dout2 <= "1101";

   -- ModuleWare code(v1.12) for instance 'U_10' of 'constval'
   din1 <= "0111";

   -- ModuleWare code(v1.12) for instance 'U_11' of 'constval'
   dout4 <= '0';

   -- ModuleWare code(v1.12) for instance 'U_12' of 'constval'
   dout5 <= '0';

   -- ModuleWare code(v1.12) for instance 'U_15' of 'constval'
   Nmoins1 <= "11111001111";

   -- ModuleWare code(v1.12) for instance 'U_16' of 'constval'
   Ndiv2 <= "01111101000";

   -- ModuleWare code(v1.12) for instance 'U_14' of 'dff'
   IdentifierField <= mw_U_14reg_cval;
   u_14seq_proc: PROCESS (H, nCLR)
   BEGIN
      IF (nCLR = '0') THEN
         mw_U_14reg_cval <= "000000";
      ELSIF (H'EVENT AND H='1') THEN
         IF (IdentifierField_EN = '1') THEN
            mw_U_14reg_cval <= RecByte_internal(5 DOWNTO 0);
         END IF;
      END IF;
   END PROCESS u_14seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_6' of 'mux'
   u_6combo_proc: PROCESS(Nmoins1, Ndiv2, n_SELECT)
   BEGIN
      CASE n_SELECT IS
      WHEN '0' => dout <= Nmoins1;
      WHEN '1' => dout <= Ndiv2;
      WHEN OTHERS => dout <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_6combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_7' of 'mux'
   u_7combo_proc: PROCESS(dout2, din1, BitsNb_SELECT)
   BEGIN
      CASE BitsNb_SELECT IS
      WHEN '0' => dout3 <= dout2;
      WHEN '1' => dout3 <= din1;
      WHEN OTHERS => dout3 <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_7combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'shiftsp'
   RecByte_internal <= mw_U_4reg_cval;
   u_4seq_proc: PROCESS (H, nCLR)
   BEGIN
      IF (nCLR = '0') THEN
         mw_U_4reg_cval <= "00000000";
      ELSIF (H'EVENT AND H='1') THEN
         IF (RecByte_EN = '1') THEN
            mw_U_4reg_cval <= mw_U_4reg_nval;
         END IF;
      END IF;
   END PROCESS u_4seq_proc;
   u_4combo_proc: PROCESS (dout6, LinSynchro_internal, mw_U_4reg_cval)
   VARIABLE temp_dout : std_logic_vector(9 DOWNTO 0);
   BEGIN
      IF (dout6 = '1') THEN
         temp_dout := LinSynchro_internal & LinSynchro_internal & mw_U_4reg_cval;
      ELSIF (dout6 = '0') THEN
         temp_dout := mw_U_4reg_cval & LinSynchro_internal & LinSynchro_internal;
      ELSE
         temp_dout := (OTHERS => 'X');
      END IF;
   mw_U_4reg_nval <= temp_dout(8 DOWNTO 1);
   END PROCESS u_4combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_5' of 'vdd'
   dout6 <= '1';

   -- Instance port mappings.
   U_13 : Decoder
      PORT MAP (
         RecByte          => RecByte_internal(5 DOWNTO 4),
         DataFieldNb_INIT => DataFieldNb_INIT
      );

   -- Implicit buffered output assignments
   LinSynchro <= LinSynchro_internal;
   RecByte    <= RecByte_internal;

END struct;
